version: "3.0"

services:
  app:
    image: johnsonlee/retracer:0.1.0
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - SPRING_PROFILE=prod
    ports:
      - "8080:8080"
    volumes:
      - "./data:/data"
